---
- name: Define yubikey_sshd_pam_config
  set_fact:
    yubikey_sshd_pam_config: |-
      {% if yubikey_sshd_and_pass -%}
      etc/pam.d/yubico-sshd-auth
      {%- else -%}
      etc/pam.d/yubico-sshd-auth-nopass
      {%- endif %}

- name: Add yubico sshd pam config
  template:
    src: "{{ yubikey_sshd_pam_config }}"
    dest: "{{ yubikey_sshd_pam }}"
    mode: 0644
    owner: root
    group: root
    backup: yes

- name: Configure sshd pam not to include common-auth or password-auth
  lineinfile:
    state: present
    dest: /etc/pam.d/sshd
    regexp: "{{ item.regex_match }}"
    line: "{{ item.line }}"
    backrefs: yes
    backup: yes
  with_items:
    - regex_match: '^@include common-auth$'
      line: '#@include common-auth'
      os_family: Debian
    - regex_match: '^(auth\s+substack\s+password-auth)$'
      line: '#\1'
      os_family: RedHat
    - regex_match: '^(auth\s+include\s+common-auth)$'
      line: '#\1'
      os_family: Suse
    - regex_match: '^(auth\s+include\s+system-remote-login)$'
      line: '#\1'
      os_family: Archlinux
  when:
    - ansible_os_family == item.os_family

- name: Configure sshd pam to include yubico-sshd-auth
  lineinfile:
    state: present
    dest: /etc/pam.d/sshd
    insertafter: "{{ item.regex_match }}"
    line: "{{ item.line }}"
    backup: yes
    create: no
  with_items:
    - regex_match: '^#@include common-auth$'
      line: '@include {{ yubikey_sshd_pam }}'
      os_family: Debian
    - regex_match: '^#auth\s+substack\s+password-auth$'
      line: 'auth include {{ yubikey_sshd_pam }}'
      os_family: RedHat
    - regex_match: '^#auth\s+include\s+common-auth$'
      line: 'auth include {{ yubikey_sshd_pam }}'
      os_family: Suse
    - regex_match: '^#auth\s+include\s+system-remote-login$'
      line: 'auth include {{ yubikey_sshd_pam }}'
      os_family: Archlinux
  when:
    - ansible_os_family == item.os_family

- name: Update sshd_config - Enable ChallengResponse Authentication
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^(#.?C|.?C)hallengeResponseAuthentication.*'
    line: 'ChallengeResponseAuthentication yes'
    backup: yes
    validate: /usr/sbin/sshd -T -f %s

- name: Update sshd_config - Disable Password Authentication
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication.*'
    line: 'PasswordAuthentication no'
    backup: yes
    validate: /usr/sbin/sshd -T -f %s

- name: Update sshd_config - Force yubikey users to use yubikey
  blockinfile:
    path: /etc/ssh/sshd_config
    state: present
    block: "{{ yubikey_sshd_config_addition }}"
    insertafter: EOF
    validate: /usr/sbin/sshd -T -f %s
  notify: restart-sshd
