---
- name: Define yubikey_sudo_pam_config
  set_fact:
    yubikey_sudo_pam_config: |-
      {% if yubikey_sudo_and_pass -%}
      etc/pam.d/yubico-sudo-auth
      {%- else -%}
      etc/pam.d/yubico-sudo-auth-nopass
      {%- endif %}

- name: Add yubico sudo pam config
  template:
    src: "{{ yubikey_sudo_pam_config }}"
    dest: "{{ yubikey_sudo_pam }}"
    mode: 0644
    owner: root
    group: root
    backup: yes

- name: Disable common-auth or system-auth within sudo pam config
  lineinfile:
    state: present
    dest: /etc/pam.d/sudo
    regexp: "{{ item.regex_match }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - regex_match: '^@include common-auth$'
      line: '#@include common-auth'
      os_family: Debian
    - regex_match: '^(auth\s+include\s+system-auth)$'
      line: '#\1'
      os_family: RedHat
    - regex_match: '^(auth\s+include\s+common-auth)$'
      line: '#\1'
      os_family: Suse
    - regex_match: '^(auth\s+include\s+system-auth)$'
      line: '#\1'
      os_family: Archlinux
  when:
    - ansible_os_family == item.os_family

- name: Enable yubico-sudo-auth within sudo pam config
  lineinfile:
    state: present
    dest: /etc/pam.d/sudo
    insertafter: "{{ item.regex_match }}"
    line: "{{ item.line }}"
    create: no
  with_items:
    - regex_match: '^#@include common-auth$'
      line: '@include yubico-sudo-auth'
      os_family: Debian
    - regex_match: '^#auth\s+include\s+system-auth$'
      line: 'auth include yubico-sudo-auth'
      os_family: RedHat
    - regex_match: '^#auth\s+include\s+common-auth$'
      line: 'auth include yubico-sudo-auth'
      os_family: Suse
    - regex_match: '^#auth\s+include\s+system-auth$'
      line: 'auth include yubico-sudo-auth'
      os_family: Archlinux
  when:
    - ansible_os_family == item.os_family
