---
- name: Add pam config for yubio auth
  template:
    src: etc/pam.d/yubico-auth
    dest: /etc/pam.d/yubico-auth
    mode: 0644
    owner: root
    group: root
    backup: yes
  tags:
    - configure
    - pam
    - yubikey

- name: Add pam config for yubio auth with nopass
  template:
    src: etc/pam.d/yubico-auth-nopass
    dest: /etc/pam.d/yubico-auth-nopass
    mode: 0644
    owner: root
    group: root
    backup: yes
  tags:
    - configure
    - pam
    - yubikey

- name: Add yubikey system group
  group:
    name: yubikey
    state: present
    system: yes
  tags:
    - configure
    - group
    - yubikey

- name: Check for sshd pam config
  stat: path=/etc/pam.d/sshd
  register: pam_sshd

- name: Configure sshd pam not to include common-auth
  lineinfile:
    state: present
    dest: /etc/pam.d/sshd
    regexp: '^@include common-auth$'
    line: '#@include common-auth'
    backrefs: yes
  when:
    - pam_yubikey_api_id is defined
    - pam_yubikey_api_key is defined
  tags:
    - configure
    - sudo
    - yubikey
    - pam

- name: Configure sshd pam to include yubico + pass auth
  lineinfile:
    state: present
    dest: /etc/pam.d/sshd
    insertbefore: '^#@include common-auth$'
    line: '@include yubico-auth'
    create: no
  when:
    - pam_yubikey_api_id is defined
    - pam_yubikey_api_key is defined
    - pam_sshd.stat.exists == True
  tags:
    - configure
    - openssh
    - yubikey
    - pam

- name: Check for sudo pam config
  stat: path=/etc/pam.d/sudo
  register: pam_sudo

- name: Configure sudo pam not to include common-auth
  lineinfile:
    state: present
    dest: /etc/pam.d/sudo
    regexp: '^@include common-auth$'
    line: '#@include common-auth'
    backrefs: yes
  when:
    - pam_yubikey_api_id is defined
    - pam_yubikey_api_key is defined
    - pam_sudo.stat.exists == True
  tags:
    - configure
    - sudo
    - yubikey
    - pam

- name: Configure sudo pam to include yubico auth
  lineinfile:
    state: present
    dest: /etc/pam.d/sudo
    insertbefore: '^#@include common-auth$'
    line: '@include yubico-auth-nopass'
    create: no
  when:
    - pam_yubikey_api_id is defined
    - pam_yubikey_api_key is defined
    - pam_sudo.stat.exists == True
  tags:
    - configure
    - sudo
    - yubikey
    - pam
