---
- name: Install libpam-yubico
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - "{{ libpam_yubico_pkg_name }}"
  tags:
    - install
    - libpam-yubico

- name: Install libsemanage-python for SELinux enable systems
  package:
    state: present
    name: libsemanage-python
  when:
    - ansible_distribution == "Fedora"
    - ansible_selinux['status'] == "enabled"
