---
- name: Install yubico pam modules
  package:
    state: present
    name: "{{ yubikey_pam_pkgs }}"

- name: Install OpenSSH Server
  package:
    state: present
    name: "{{ yubikey_sshd_pkgs }}"
  when: yubikey_config_sshd|default(false)
  notify: ssh-keygen hostkeys

- meta: flush_handlers

- name: Install libsemanage-python for SELinux enable systems
  package:
    state: present
    name: libsemanage-python
  when:
    - ansible_distribution == "Fedora"
    - ansible_selinux['status']|default('disabled') == "enabled"
