---
- name: Converge
  hosts: all
  vars:
    yubikey_config_login: true
    yubikey_sudo_and_pass: false
    yubikey_sshd_and_pass: true
    yubikey_sudo_chal_rsp: false
  tasks:
    - include_vars: main.yml

    - name: Add sshd privilege seperation dir
      file:
        path: /run/sshd
        state: directory

    - name: Add user
      user:
        name: hurricane
        append: yes
        shell: /bin/bash
        create_home: yes
        password: '$6$Dz7DRuGe$gJekeA67Ezp0raeRoS3AL6In2MpQ6z/tiY4w6b/xoyk0X8f/yNsOYNsBnVqnzlP643lGW6tvVRXvaJrmvqGR/0'

    - name: Run ansible-pam_yubikey role
      include_role:
        name: ansible-pam_yubikey
